blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://mathiaspaulenko.github.io/behave-runner/
    about: Read the docs before opening an issue.
  - name: Discussions
    url: https://github.com/MathiasPaulenko/behave-runner/discussions
    about: Ask questions and discuss ideas in Discussions.
